### ISSUE TITLE
-exclude option

### ISSUE THREAD

**Issue by xif-fr** [xif-fr/dokuwiki-plugin-catlist#26]
To do.

**Comment by ajfclark** [comment]
You should remove this from the documentation list here: https://www.dokuwiki.org/plugin:catlist

I just spent an hour or two trying to figure out the namespace error message going over and over this only to finally notice italic line that says it's not implemented.

**Comment by IFD3** [comment]
Oh man ... yeah me too.
Well at least I know now to stop looking, thanks @ajfclark !

**Comment by xif-fr** [comment]
Well, I'm now working on this, it should be implemented very soon.

**Comment by xif-fr** [comment]
Done.

**Comment by ajfclark** [comment]
Thanks for jumping on this so quickly!

Plugin doesn't show as updatable in my dokuwiki extension manager, and the https://www.dokuwiki.org/plugin:catlist page still shows the latest update as 2021-02-04.

Will this fix get pushed there or do I need to manually update the plugin?

**Comment by xif-fr** [comment]
I just pushed the new version right now. Tell me if it works for you !

**Comment by IFD3** [comment]
Still getting this with the latest Version:
Unknown option -exclude:“Sidebar” for <catlist>
Unknown option -exclupage:“Sidebar” for <catlist>

**Comment by xif-fr** [comment]
What is the full syntax you are using ? The syntax for the -exclude option is `-exclude:{sidebar}` (if the namespace **id** is `sidebar`). Maybe the documentation is not clear enough ?

**Comment by xif-fr** [comment]
However for the -exclupage option, the syntax you are using is right. Maybe you are using `-exclupage:“Sidebar”` rather than `-exclupage:"Sidebar"` ? Pay attention to the **quotes**, I guess you just copy-pasted from the dokuwiki page, which does not display the right quotes.

**Comment by xif-fr** [comment]
I fixed the quotation marks on the documentation so that they are the right ones.
